server:
  port: ${PORT:31001}
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri: mongodb://47.101.34.81:27017
      database: xc_cms2
  rabbitmq:
    host: 47.101.34.81
    port: 5672
    username: admin
    password: admin
    virtual-host: /
xuecheng:
  mq:
    queue: queue_cms_postpage_01
    routingKey: 5a751fab6abb5044e0d19ea1  #门户站点的id
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA-SERVER:http://eureka01:50101/eureka/,http://eureka02:50102/eureka/}
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    ip-address: ${IP_ADDRESS:127.0.0.1}
