server:
  port: ${port:40100}
spring:
  application:
    name: xc-service-search
xuecheng:
  elasticsearch:
#    hostlist: ${eshostlist:47.101.34.81:9200} #多个结点中间用逗号分隔
    hostlist: ${eshostlist:47.105.67.144:9200} #多个结点中间用逗号分隔
    course:
#      index: xuecheng                         #索引库名称
      index: zsh_xuecheng                         #索引库名称
      type: doc                               #类型,没有实际意义
      source_field: id,name,grade,mt,st,charge,valid,pic,qq,price,price_old,status,studymodel,teachmode,expires,pub_time,start_time,end_time,teachplan
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA-SERVER:http://eureka01:50101/eureka/,http://eureka02:50102/eureka/}
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    ip-address: ${IP_ADDRESS:127.0.0.1}
ribbon:
  MaxAutoRetriesNextServer: 3 #切换实例的重试次数
  OkToRetryOnAl lOperations: false #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作 没有实现幂等的情况下是很危险的,所以设置为false
  ConnectTimeout: 5000 #请求连接的超时时间
  ReadTimeout: 6000 #请求处理的超时时间