server:
  port: 31450
spring:
  application:
    name: xc-service-manage-media-processor
  data:
    mongodb:
      uri:  mongodb://47.101.34.81:27017
      database: xc_media
#rabbitmq配置
  rabbitmq:
    host: 47.101.34.81
    port: 5672
    username: admin
    password: admin
    virtual-host: /
xc-service-manage-media:
  mq:
    queue-media-video-processor: queue_media_video_processor
    routingkey-media-video: routingkey_media_video
  video-location: E:/idea_code/Learning_online/develop/video/
  ffmpeg-path: E:/FFmpeg/ffmpeg-20180227-fa0c9d6-win64-static/bin/ffmpeg.exe